/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Pedido;

import Vista.Usuario.*;
import Controlador.controladorBaseDatos;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author joseluis.caamal
 */
public class vistaAgregarPedido extends javax.swing.JDialog {

    /**
     * Creates new form vistaAgregarPuesto
     */
    public static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd h:mm", Locale.US);
    public static SimpleDateFormat sdfResult = new SimpleDateFormat("HH:mm:ss", Locale.US);
    public static SimpleDateFormat sdfResultMinutos = new SimpleDateFormat("m", Locale.US);
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloComboS = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloComboE = new DefaultComboBoxModel();
    controladorBaseDatos cbd = new controladorBaseDatos();
    public vistaAgregarPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        campoArreglo.removeAllItems();
        campoEstatus.removeAllItems();
        campoEmpleado.removeAllItems();
        cbd.openConnection();
        llenar_comboSt();
        cbd.closeConnection();
        cbd.openConnection();
        llenar_comboA();
        cbd.closeConnection();
        cbd.openConnection();
        llenar_comboE();
        cbd.closeConnection();
    }
    
    public void llenar_comboSt() {
        String Sql = "Select * from tabla_estatus";
        try {
            
            PreparedStatement us = cbd.Conexion.prepareStatement(Sql);
            ResultSet res = us.executeQuery(); //
            //modeloCombo.addElement("Seleccione un Campo");//es el primer registro q mostrara el combo
            modeloCombo.addElement("Seleccione un Campo");
            campoEstatus.setModel(modeloCombo);//con esto lo agregamos al objeto al jcombobox
                while (res.next()) {
                        System.out.println(res.getObject("Name"));
                       modeloCombo.addElement(res.getObject("Name"));
                       campoEstatus.setModel(modeloCombo);//con esto lo agregamos al objeto al jcombobox
                }
                res.close();
            }
            catch(SQLException ex){
                System.out.println(ex.getMessage());
            }
    }
    public void llenar_comboA() {
        String Sql = "Select * from tabla_arreglos";
        try {
            
            PreparedStatement us = cbd.Conexion.prepareStatement(Sql);
            ResultSet res = us.executeQuery(); //
            //modeloCombo.addElement("Seleccione un Campo");//es el primer registro q mostrara el combo
            campoArreglo.setModel(modeloComboS);//con esto lo agregamos al objeto al jcombobox
            modeloComboS.addElement("Seleccione un Campo");
                while (res.next()) {
                        System.out.println(res.getObject("nombre"));
                       modeloComboS.addElement(res.getObject("nombre"));
                       campoArreglo.setModel(modeloComboS);//con esto lo agregamos al objeto al jcombobox
                }
                res.close();
            }
            catch(SQLException ex){
                System.out.println(ex.getMessage());
            }
    }
    
    public void llenar_comboE() {
        String Sql = "Select * from tabla_empleados WHERE puesto = 1";
        try {
            
            PreparedStatement us = cbd.Conexion.prepareStatement(Sql);
            ResultSet res = us.executeQuery(); //
            //modeloCombo.addElement("Seleccione un Campo");//es el primer registro q mostrara el combo
            campoEmpleado.setModel(modeloComboE);//con esto lo agregamos al objeto al jcombobox
            modeloComboE.addElement("Seleccione un Campo");
                while (res.next()) {
                       System.out.println(res.getObject("num_empleado"));
                       modeloComboE.addElement(res.getObject("num_empleado"));
                       campoEmpleado.setModel(modeloComboE);//con esto lo agregamos al objeto al jcombobox
                }
                res.close();
            }
            catch(SQLException ex){
                System.out.println(ex.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeInicio = new cambodia.raven.Time();
        timeFin = new cambodia.raven.Time();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoTiempoEstimado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoArreglo = new javax.swing.JComboBox<>();
        campoEstatus = new javax.swing.JComboBox<>();
        campoInicio = new com.toedter.calendar.JDateChooser();
        campoFin = new com.toedter.calendar.JDateChooser();
        campoEmpleado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tiempo Estimado");

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Catalógo Pedidos: Insertar Pedido");

        campoTiempoEstimado.setEditable(false);

        jLabel3.setText("N. Empleado");

        jLabel6.setText("Arreglo");

        jLabel7.setText("Estatus");

        jLabel8.setText("Hora Inicio");

        jLabel9.setText("Hora Fin");

        campoArreglo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        campoArreglo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campoArregloItemStateChanged(evt);
            }
        });

        campoEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        campoInicio.setEnabled(false);

        campoFin.setEnabled(false);

        campoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("*Nota: La fecha se añadira por defecto .");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoTiempoEstimado)
                            .addComponent(campoArreglo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoEstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoFin, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(campoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTiempoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int operacionExitoso = 0;
        if(campoEstatus.getSelectedIndex() != 0 && campoArreglo.getSelectedIndex() !=0 && campoEmpleado.getSelectedIndex() !=0){
            
            cbd.openConnection();
//            Date diferencia = cbd.diferenciaFechas(campoInicio.getDate(), campoFin.getDate());
//            System.out.println(sdfResult.format(diferencia)); //00:02:00
//            System.out.println(sdfResultMinutos.format(diferencia) + " Minutos"); //2 Minutos
//            int percent = ((Integer.parseInt(campoTiempoEstimado.getText())/100)*90);
//            if(percent > Integer.parseInt(sdfResultMinutos.format(diferencia))){
//                JOptionPane.showMessageDialog(null, " Aviso: La estimación final supera el 90% para terminar con el pedido");
//            }
                operacionExitoso = cbd.insertarPedidos((int) campoEmpleado.getSelectedItem(),
                    campoArreglo.getSelectedIndex(),
                    campoEstatus.getSelectedIndex(),
                    Integer.parseInt(campoTiempoEstimado.getText()),
                    new Date(),
                    new Date());
                cbd.closeConnection();
                if(operacionExitoso == 1){
                    JOptionPane.showMessageDialog(null, "Proceso Exitoso : "+campoEmpleado.getSelectedIndex());
                }
                else{
                    JOptionPane.showMessageDialog(null, "Proceso, No Exitoso: "+campoEmpleado.getSelectedIndex());
                }
                this.dispose();
        }
        else{

            JOptionPane.showMessageDialog(null, "Selecciona un campo en Estatus,Empleado y Arreglo Floral");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoArregloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campoArregloItemStateChanged
        // TODO add your handling code here:
       //cbd.obtenTiempoEstimado(campoArreglo.getSelectedIndex());
       cbd.openConnection();
                if ( evt.getStateChange() == ItemEvent.SELECTED ) 
                {
                    int item = campoArreglo.getSelectedIndex();
                    item = cbd.obtenTiempoEstimado(item);
                    System.out.println("El item es:"+item);
                    campoTiempoEstimado.setText(String.valueOf(item));
                    
                }
       cbd.closeConnection();
    }//GEN-LAST:event_campoArregloItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vistaAgregarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vistaAgregarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vistaAgregarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vistaAgregarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                vistaAgregarUsuario dialog = new vistaAgregarUsuario;
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> campoArreglo;
    private javax.swing.JComboBox<String> campoEmpleado;
    private javax.swing.JComboBox<String> campoEstatus;
    private com.toedter.calendar.JDateChooser campoFin;
    private com.toedter.calendar.JDateChooser campoInicio;
    private javax.swing.JTextField campoTiempoEstimado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private cambodia.raven.Time timeFin;
    private cambodia.raven.Time timeInicio;
    // End of variables declaration//GEN-END:variables
}
