/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.modeloUsuario;
import Vista.Pedido.vistaPedidos;
import Vista.Puesto.vistaPuestos;
import Vista.Supervisor.vistaSupervisor;
import Vista.Usuario.vistaUsuarios;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author joseluis.caamal
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
    }
    modeloUsuario mu = new modeloUsuario();
    public vistaPrincipal(modeloUsuario modeloUsuario) {
        initComponents();
        campoUsuario.setText(modeloUsuario.getNombre());
        mu = modeloUsuario; //Asigno el valor actual del usuario que inicio sesión
        String tipoUsuario = "";
        switch(modeloUsuario.getPuesto()){
        
            case 1:
                tipoUsuario = "diseñador";
                btnCatalogoUsuarios.setEnabled(false);
                btnCatalogoPuestos.setEnabled(false);
                btnCatalogoSupervisor.setEnabled(false);
            break;
            case 2:
                tipoUsuario = "supervisor";
                btnCatalogoPedidos.setEnabled(false);
                btnCatalogoUsuarios.setEnabled(false);
                btnCatalogoPuestos.setEnabled(false);
            break;
            case 3:
                tipoUsuario = "administrador";
            break;
        }
        campoTipoUsuario.setText(tipoUsuario);
        campoNumEmpleado.setText(String.valueOf(modeloUsuario.getNum_empleado()));
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        etiquetaHora.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JLabel();
        campoTipoUsuario = new javax.swing.JLabel();
        campoNumEmpleado = new javax.swing.JLabel();
        btnCatalogoPuestos = new javax.swing.JButton();
        btnCatalogoUsuarios = new javax.swing.JButton();
        btnCatalogoPedidos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        etiquetaHora = new javax.swing.JLabel();
        btnCatalogoSupervisor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Panel Principal");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Tipo Usuario:");

        jLabel4.setText("Num. Empleado:");

        campoUsuario.setText("jLabel5");

        campoTipoUsuario.setText("jLabel5");

        campoNumEmpleado.setText("jLabel5");

        btnCatalogoPuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gasvalid_changemain.png"))); // NOI18N
        btnCatalogoPuestos.setText("Puestos");
        btnCatalogoPuestos.setToolTipText("Catalogo Puestos");
        btnCatalogoPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoPuestosActionPerformed(evt);
            }
        });

        btnCatalogoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_group.png"))); // NOI18N
        btnCatalogoUsuarios.setText("Usuarios");
        btnCatalogoUsuarios.setToolTipText("Catalogo Usuarios");
        btnCatalogoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoUsuariosActionPerformed(evt);
            }
        });

        btnCatalogoPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contract_pencil.png"))); // NOI18N
        btnCatalogoPedidos.setText("Pedidos");
        btnCatalogoPedidos.setToolTipText("Catalogo Pedidos");
        btnCatalogoPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoPedidosActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("*Nota: Algunas funcionalidades están desactivadas para algunos usuarios, consulte con el administrador.");

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha:");

        etiquetaHora.setText("jLabel7");

        btnCatalogoSupervisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/super.png"))); // NOI18N
        btnCatalogoSupervisor.setText("Supervisor");
        btnCatalogoSupervisor.setToolTipText("Catalogo Puestos");
        btnCatalogoSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoSupervisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(campoUsuario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campoTipoUsuario)))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaHora))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(campoNumEmpleado)))))
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCatalogoSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCatalogoUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnCatalogoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(btnCatalogoPuestos)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(campoUsuario)
                    .addComponent(campoNumEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoTipoUsuario)
                    .addComponent(jLabel6)
                    .addComponent(etiquetaHora))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCatalogoPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCatalogoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCatalogoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCatalogoSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaInicioSesion vis = new vistaInicioSesion();
        vis.show();
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCatalogoPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoPedidosActionPerformed
        // TODO add your handling code here:
        vistaPedidos vp = new vistaPedidos(mu);
        vp.show();
    }//GEN-LAST:event_btnCatalogoPedidosActionPerformed

    private void btnCatalogoPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoPuestosActionPerformed
        // TODO add your handling code here:
        vistaPuestos vp = new vistaPuestos();
        vp.show();
    }//GEN-LAST:event_btnCatalogoPuestosActionPerformed

    private void btnCatalogoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoUsuariosActionPerformed
        // TODO add your handling code here:
        vistaUsuarios vu = new vistaUsuarios();
        vu.show();
    }//GEN-LAST:event_btnCatalogoUsuariosActionPerformed

    private void btnCatalogoSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoSupervisorActionPerformed
        // TODO add your handling code here:
        vistaSupervisor vs = new vistaSupervisor(mu);
        vs.show();
    }//GEN-LAST:event_btnCatalogoSupervisorActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vistaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogoPedidos;
    private javax.swing.JButton btnCatalogoPuestos;
    private javax.swing.JButton btnCatalogoSupervisor;
    private javax.swing.JButton btnCatalogoUsuarios;
    private javax.swing.JToggleButton btnCerrarSesion;
    private javax.swing.JLabel campoNumEmpleado;
    private javax.swing.JLabel campoTipoUsuario;
    private javax.swing.JLabel campoUsuario;
    private javax.swing.JLabel etiquetaHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
